/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedConverterRouteImport } from './routes/_authed/converter'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups/index'
import { Route as AuthedGoalsIndexRouteImport } from './routes/_authed/goals/index'
import { Route as AuthedhomeIndexRouteImport } from './routes/_authed/(home)/index'
import { Route as AuthedGroupsNewRouteImport } from './routes/_authed/groups/new'
import { Route as AuthedIInviteCodeIndexRouteImport } from './routes/_authed/i/$inviteCode/index'
import { Route as AuthedGroupsNewIndexRouteImport } from './routes/_authed/groups/new/index'
import { Route as AuthedGroupsIdIndexRouteImport } from './routes/_authed/groups/$id/index'
import { Route as AuthedGoalsNewIndexRouteImport } from './routes/_authed/goals/new/index'
import { Route as AuthedGoalsIdIndexRouteImport } from './routes/_authed/goals/$id/index'
import { Route as AuthedGroupsNewParticipantsRouteImport } from './routes/_authed/groups/new/participants'
import { Route as AuthedGroupsIdSettleRouteImport } from './routes/_authed/groups/$id/settle'
import { Route as AuthedGroupsIdParticipantsRouteImport } from './routes/_authed/groups/$id/participants'
import { Route as AuthedGroupsIdBalancesIndexRouteImport } from './routes/_authed/groups/$id/balances/index'
import { Route as AuthedGroupsIdAddExpenseIndexRouteImport } from './routes/_authed/groups/$id/add-expense/index'
import { Route as AuthedGroupsIdExpenseExpenseIdRouteImport } from './routes/_authed/groups/$id/expense/$expenseId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedConverterRoute = AuthedConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => AuthedRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGoalsIndexRoute = AuthedGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedhomeIndexRoute = AuthedhomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsNewRoute = AuthedGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIInviteCodeIndexRoute = AuthedIInviteCodeIndexRouteImport.update({
  id: '/i/$inviteCode/',
  path: '/i/$inviteCode/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsNewIndexRoute = AuthedGroupsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedGroupsNewRoute,
} as any)
const AuthedGroupsIdIndexRoute = AuthedGroupsIdIndexRouteImport.update({
  id: '/groups/$id/',
  path: '/groups/$id/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGoalsNewIndexRoute = AuthedGoalsNewIndexRouteImport.update({
  id: '/goals/new/',
  path: '/goals/new/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGoalsIdIndexRoute = AuthedGoalsIdIndexRouteImport.update({
  id: '/goals/$id/',
  path: '/goals/$id/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsNewParticipantsRoute =
  AuthedGroupsNewParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthedGroupsNewRoute,
  } as any)
const AuthedGroupsIdSettleRoute = AuthedGroupsIdSettleRouteImport.update({
  id: '/groups/$id/settle',
  path: '/groups/$id/settle',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsIdParticipantsRoute =
  AuthedGroupsIdParticipantsRouteImport.update({
    id: '/groups/$id/participants',
    path: '/groups/$id/participants',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIdBalancesIndexRoute =
  AuthedGroupsIdBalancesIndexRouteImport.update({
    id: '/groups/$id/balances/',
    path: '/groups/$id/balances/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIdAddExpenseIndexRoute =
  AuthedGroupsIdAddExpenseIndexRouteImport.update({
    id: '/groups/$id/add-expense/',
    path: '/groups/$id/add-expense/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIdExpenseExpenseIdRoute =
  AuthedGroupsIdExpenseExpenseIdRouteImport.update({
    id: '/groups/$id/expense/$expenseId',
    path: '/groups/$id/expense/$expenseId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedhomeIndexRoute
  '/converter': typeof AuthedConverterRoute
  '/groups/new': typeof AuthedGroupsNewRouteWithChildren
  '/goals/': typeof AuthedGoalsIndexRoute
  '/groups/': typeof AuthedGroupsIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/login/': typeof PublicLoginIndexRoute
  '/groups/$id/participants': typeof AuthedGroupsIdParticipantsRoute
  '/groups/$id/settle': typeof AuthedGroupsIdSettleRoute
  '/groups/new/participants': typeof AuthedGroupsNewParticipantsRoute
  '/goals/$id/': typeof AuthedGoalsIdIndexRoute
  '/goals/new/': typeof AuthedGoalsNewIndexRoute
  '/groups/$id/': typeof AuthedGroupsIdIndexRoute
  '/groups/new/': typeof AuthedGroupsNewIndexRoute
  '/i/$inviteCode/': typeof AuthedIInviteCodeIndexRoute
  '/groups/$id/expense/$expenseId': typeof AuthedGroupsIdExpenseExpenseIdRoute
  '/groups/$id/add-expense/': typeof AuthedGroupsIdAddExpenseIndexRoute
  '/groups/$id/balances/': typeof AuthedGroupsIdBalancesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedhomeIndexRoute
  '/converter': typeof AuthedConverterRoute
  '/goals': typeof AuthedGoalsIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/groups/$id/participants': typeof AuthedGroupsIdParticipantsRoute
  '/groups/$id/settle': typeof AuthedGroupsIdSettleRoute
  '/groups/new/participants': typeof AuthedGroupsNewParticipantsRoute
  '/goals/$id': typeof AuthedGoalsIdIndexRoute
  '/goals/new': typeof AuthedGoalsNewIndexRoute
  '/groups/$id': typeof AuthedGroupsIdIndexRoute
  '/groups/new': typeof AuthedGroupsNewIndexRoute
  '/i/$inviteCode': typeof AuthedIInviteCodeIndexRoute
  '/groups/$id/expense/$expenseId': typeof AuthedGroupsIdExpenseExpenseIdRoute
  '/groups/$id/add-expense': typeof AuthedGroupsIdAddExpenseIndexRoute
  '/groups/$id/balances': typeof AuthedGroupsIdBalancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authed/converter': typeof AuthedConverterRoute
  '/_authed/groups/new': typeof AuthedGroupsNewRouteWithChildren
  '/_authed/(home)/': typeof AuthedhomeIndexRoute
  '/_authed/goals/': typeof AuthedGoalsIndexRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_authed/groups/$id/participants': typeof AuthedGroupsIdParticipantsRoute
  '/_authed/groups/$id/settle': typeof AuthedGroupsIdSettleRoute
  '/_authed/groups/new/participants': typeof AuthedGroupsNewParticipantsRoute
  '/_authed/goals/$id/': typeof AuthedGoalsIdIndexRoute
  '/_authed/goals/new/': typeof AuthedGoalsNewIndexRoute
  '/_authed/groups/$id/': typeof AuthedGroupsIdIndexRoute
  '/_authed/groups/new/': typeof AuthedGroupsNewIndexRoute
  '/_authed/i/$inviteCode/': typeof AuthedIInviteCodeIndexRoute
  '/_authed/groups/$id/expense/$expenseId': typeof AuthedGroupsIdExpenseExpenseIdRoute
  '/_authed/groups/$id/add-expense/': typeof AuthedGroupsIdAddExpenseIndexRoute
  '/_authed/groups/$id/balances/': typeof AuthedGroupsIdBalancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/converter'
    | '/groups/new'
    | '/goals/'
    | '/groups/'
    | '/profile/'
    | '/login/'
    | '/groups/$id/participants'
    | '/groups/$id/settle'
    | '/groups/new/participants'
    | '/goals/$id/'
    | '/goals/new/'
    | '/groups/$id/'
    | '/groups/new/'
    | '/i/$inviteCode/'
    | '/groups/$id/expense/$expenseId'
    | '/groups/$id/add-expense/'
    | '/groups/$id/balances/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/converter'
    | '/goals'
    | '/groups'
    | '/profile'
    | '/login'
    | '/groups/$id/participants'
    | '/groups/$id/settle'
    | '/groups/new/participants'
    | '/goals/$id'
    | '/goals/new'
    | '/groups/$id'
    | '/groups/new'
    | '/i/$inviteCode'
    | '/groups/$id/expense/$expenseId'
    | '/groups/$id/add-expense'
    | '/groups/$id/balances'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/converter'
    | '/_authed/groups/new'
    | '/_authed/(home)/'
    | '/_authed/goals/'
    | '/_authed/groups/'
    | '/_authed/profile/'
    | '/_public/login/'
    | '/_authed/groups/$id/participants'
    | '/_authed/groups/$id/settle'
    | '/_authed/groups/new/participants'
    | '/_authed/goals/$id/'
    | '/_authed/goals/new/'
    | '/_authed/groups/$id/'
    | '/_authed/groups/new/'
    | '/_authed/i/$inviteCode/'
    | '/_authed/groups/$id/expense/$expenseId'
    | '/_authed/groups/$id/add-expense/'
    | '/_authed/groups/$id/balances/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/converter': {
      id: '/_authed/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof AuthedConverterRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/goals/': {
      id: '/_authed/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthedGoalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/(home)/': {
      id: '/_authed/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedhomeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/new': {
      id: '/_authed/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AuthedGroupsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/i/$inviteCode/': {
      id: '/_authed/i/$inviteCode/'
      path: '/i/$inviteCode'
      fullPath: '/i/$inviteCode/'
      preLoaderRoute: typeof AuthedIInviteCodeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/new/': {
      id: '/_authed/groups/new/'
      path: '/'
      fullPath: '/groups/new/'
      preLoaderRoute: typeof AuthedGroupsNewIndexRouteImport
      parentRoute: typeof AuthedGroupsNewRoute
    }
    '/_authed/groups/$id/': {
      id: '/_authed/groups/$id/'
      path: '/groups/$id'
      fullPath: '/groups/$id/'
      preLoaderRoute: typeof AuthedGroupsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/goals/new/': {
      id: '/_authed/goals/new/'
      path: '/goals/new'
      fullPath: '/goals/new/'
      preLoaderRoute: typeof AuthedGoalsNewIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/goals/$id/': {
      id: '/_authed/goals/$id/'
      path: '/goals/$id'
      fullPath: '/goals/$id/'
      preLoaderRoute: typeof AuthedGoalsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/new/participants': {
      id: '/_authed/groups/new/participants'
      path: '/participants'
      fullPath: '/groups/new/participants'
      preLoaderRoute: typeof AuthedGroupsNewParticipantsRouteImport
      parentRoute: typeof AuthedGroupsNewRoute
    }
    '/_authed/groups/$id/settle': {
      id: '/_authed/groups/$id/settle'
      path: '/groups/$id/settle'
      fullPath: '/groups/$id/settle'
      preLoaderRoute: typeof AuthedGroupsIdSettleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/participants': {
      id: '/_authed/groups/$id/participants'
      path: '/groups/$id/participants'
      fullPath: '/groups/$id/participants'
      preLoaderRoute: typeof AuthedGroupsIdParticipantsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/balances/': {
      id: '/_authed/groups/$id/balances/'
      path: '/groups/$id/balances'
      fullPath: '/groups/$id/balances/'
      preLoaderRoute: typeof AuthedGroupsIdBalancesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/add-expense/': {
      id: '/_authed/groups/$id/add-expense/'
      path: '/groups/$id/add-expense'
      fullPath: '/groups/$id/add-expense/'
      preLoaderRoute: typeof AuthedGroupsIdAddExpenseIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/expense/$expenseId': {
      id: '/_authed/groups/$id/expense/$expenseId'
      path: '/groups/$id/expense/$expenseId'
      fullPath: '/groups/$id/expense/$expenseId'
      preLoaderRoute: typeof AuthedGroupsIdExpenseExpenseIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedGroupsNewRouteChildren {
  AuthedGroupsNewParticipantsRoute: typeof AuthedGroupsNewParticipantsRoute
  AuthedGroupsNewIndexRoute: typeof AuthedGroupsNewIndexRoute
}

const AuthedGroupsNewRouteChildren: AuthedGroupsNewRouteChildren = {
  AuthedGroupsNewParticipantsRoute: AuthedGroupsNewParticipantsRoute,
  AuthedGroupsNewIndexRoute: AuthedGroupsNewIndexRoute,
}

const AuthedGroupsNewRouteWithChildren = AuthedGroupsNewRoute._addFileChildren(
  AuthedGroupsNewRouteChildren,
)

interface AuthedRouteChildren {
  AuthedConverterRoute: typeof AuthedConverterRoute
  AuthedGroupsNewRoute: typeof AuthedGroupsNewRouteWithChildren
  AuthedhomeIndexRoute: typeof AuthedhomeIndexRoute
  AuthedGoalsIndexRoute: typeof AuthedGoalsIndexRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
  AuthedGroupsIdParticipantsRoute: typeof AuthedGroupsIdParticipantsRoute
  AuthedGroupsIdSettleRoute: typeof AuthedGroupsIdSettleRoute
  AuthedGoalsIdIndexRoute: typeof AuthedGoalsIdIndexRoute
  AuthedGoalsNewIndexRoute: typeof AuthedGoalsNewIndexRoute
  AuthedGroupsIdIndexRoute: typeof AuthedGroupsIdIndexRoute
  AuthedIInviteCodeIndexRoute: typeof AuthedIInviteCodeIndexRoute
  AuthedGroupsIdExpenseExpenseIdRoute: typeof AuthedGroupsIdExpenseExpenseIdRoute
  AuthedGroupsIdAddExpenseIndexRoute: typeof AuthedGroupsIdAddExpenseIndexRoute
  AuthedGroupsIdBalancesIndexRoute: typeof AuthedGroupsIdBalancesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedConverterRoute: AuthedConverterRoute,
  AuthedGroupsNewRoute: AuthedGroupsNewRouteWithChildren,
  AuthedhomeIndexRoute: AuthedhomeIndexRoute,
  AuthedGoalsIndexRoute: AuthedGoalsIndexRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
  AuthedGroupsIdParticipantsRoute: AuthedGroupsIdParticipantsRoute,
  AuthedGroupsIdSettleRoute: AuthedGroupsIdSettleRoute,
  AuthedGoalsIdIndexRoute: AuthedGoalsIdIndexRoute,
  AuthedGoalsNewIndexRoute: AuthedGoalsNewIndexRoute,
  AuthedGroupsIdIndexRoute: AuthedGroupsIdIndexRoute,
  AuthedIInviteCodeIndexRoute: AuthedIInviteCodeIndexRoute,
  AuthedGroupsIdExpenseExpenseIdRoute: AuthedGroupsIdExpenseExpenseIdRoute,
  AuthedGroupsIdAddExpenseIndexRoute: AuthedGroupsIdAddExpenseIndexRoute,
  AuthedGroupsIdBalancesIndexRoute: AuthedGroupsIdBalancesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
