/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedGroupsIndexRouteImport } from './routes/_authed/groups/index'
import { Route as AuthedGoalsIndexRouteImport } from './routes/_authed/goals/index'
import { Route as AuthedhomeIndexRouteImport } from './routes/_authed/(home)/index'
import { Route as AuthedGroupsNewRouteImport } from './routes/_authed/groups/new'
import { Route as AuthedGroupsNewIndexRouteImport } from './routes/_authed/groups/new/index'
import { Route as AuthedGroupsNewParticipantsRouteImport } from './routes/_authed/groups/new/participants'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsIndexRoute = AuthedGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGoalsIndexRoute = AuthedGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedhomeIndexRoute = AuthedhomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsNewRoute = AuthedGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsNewIndexRoute = AuthedGroupsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedGroupsNewRoute,
} as any)
const AuthedGroupsNewParticipantsRoute =
  AuthedGroupsNewParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthedGroupsNewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedhomeIndexRoute
  '/groups/new': typeof AuthedGroupsNewRouteWithChildren
  '/goals/': typeof AuthedGoalsIndexRoute
  '/groups/': typeof AuthedGroupsIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/login/': typeof PublicLoginIndexRoute
  '/groups/new/participants': typeof AuthedGroupsNewParticipantsRoute
  '/groups/new/': typeof AuthedGroupsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedhomeIndexRoute
  '/goals': typeof AuthedGoalsIndexRoute
  '/groups': typeof AuthedGroupsIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/groups/new/participants': typeof AuthedGroupsNewParticipantsRoute
  '/groups/new': typeof AuthedGroupsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authed/groups/new': typeof AuthedGroupsNewRouteWithChildren
  '/_authed/(home)/': typeof AuthedhomeIndexRoute
  '/_authed/goals/': typeof AuthedGoalsIndexRoute
  '/_authed/groups/': typeof AuthedGroupsIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_authed/groups/new/participants': typeof AuthedGroupsNewParticipantsRoute
  '/_authed/groups/new/': typeof AuthedGroupsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/groups/new'
    | '/goals/'
    | '/groups/'
    | '/profile/'
    | '/login/'
    | '/groups/new/participants'
    | '/groups/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/goals'
    | '/groups'
    | '/profile'
    | '/login'
    | '/groups/new/participants'
    | '/groups/new'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_authed/groups/new'
    | '/_authed/(home)/'
    | '/_authed/goals/'
    | '/_authed/groups/'
    | '/_authed/profile/'
    | '/_public/login/'
    | '/_authed/groups/new/participants'
    | '/_authed/groups/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/': {
      id: '/_authed/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedGroupsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/goals/': {
      id: '/_authed/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthedGoalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/(home)/': {
      id: '/_authed/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedhomeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/new': {
      id: '/_authed/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof AuthedGroupsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/new/': {
      id: '/_authed/groups/new/'
      path: '/'
      fullPath: '/groups/new/'
      preLoaderRoute: typeof AuthedGroupsNewIndexRouteImport
      parentRoute: typeof AuthedGroupsNewRoute
    }
    '/_authed/groups/new/participants': {
      id: '/_authed/groups/new/participants'
      path: '/participants'
      fullPath: '/groups/new/participants'
      preLoaderRoute: typeof AuthedGroupsNewParticipantsRouteImport
      parentRoute: typeof AuthedGroupsNewRoute
    }
  }
}

interface AuthedGroupsNewRouteChildren {
  AuthedGroupsNewParticipantsRoute: typeof AuthedGroupsNewParticipantsRoute
  AuthedGroupsNewIndexRoute: typeof AuthedGroupsNewIndexRoute
}

const AuthedGroupsNewRouteChildren: AuthedGroupsNewRouteChildren = {
  AuthedGroupsNewParticipantsRoute: AuthedGroupsNewParticipantsRoute,
  AuthedGroupsNewIndexRoute: AuthedGroupsNewIndexRoute,
}

const AuthedGroupsNewRouteWithChildren = AuthedGroupsNewRoute._addFileChildren(
  AuthedGroupsNewRouteChildren,
)

interface AuthedRouteChildren {
  AuthedGroupsNewRoute: typeof AuthedGroupsNewRouteWithChildren
  AuthedhomeIndexRoute: typeof AuthedhomeIndexRoute
  AuthedGoalsIndexRoute: typeof AuthedGoalsIndexRoute
  AuthedGroupsIndexRoute: typeof AuthedGroupsIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedGroupsNewRoute: AuthedGroupsNewRouteWithChildren,
  AuthedhomeIndexRoute: AuthedhomeIndexRoute,
  AuthedGoalsIndexRoute: AuthedGoalsIndexRoute,
  AuthedGroupsIndexRoute: AuthedGroupsIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
