/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as PublicWelcomeIndexRouteImport } from './routes/_public/welcome/index'
import { Route as AuthedhomeIndexRouteImport } from './routes/_authed/(home)/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedGroupsNewIndexRouteImport } from './routes/_authed/groups/new/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicWelcomeIndexRoute = PublicWelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedhomeIndexRoute = AuthedhomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedGroupsNewIndexRoute = AuthedGroupsNewIndexRouteImport.update({
  id: '/groups/new/',
  path: '/groups/new/',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedhomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/welcome/': typeof PublicWelcomeIndexRoute
  '/groups/new/': typeof AuthedGroupsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedhomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/welcome': typeof PublicWelcomeIndexRoute
  '/groups/new': typeof AuthedGroupsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/(home)/': typeof AuthedhomeIndexRoute
  '/_public/welcome/': typeof PublicWelcomeIndexRoute
  '/_authed/groups/new/': typeof AuthedGroupsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth/$' | '/welcome/' | '/groups/new/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth/$' | '/welcome' | '/groups/new'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/api/auth/$'
    | '/_authed/(home)/'
    | '/_public/welcome/'
    | '/_authed/groups/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/welcome/': {
      id: '/_public/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof PublicWelcomeIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/(home)/': {
      id: '/_authed/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedhomeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/groups/new/': {
      id: '/_authed/groups/new/'
      path: '/groups/new'
      fullPath: '/groups/new/'
      preLoaderRoute: typeof AuthedGroupsNewIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedhomeIndexRoute: typeof AuthedhomeIndexRoute
  AuthedGroupsNewIndexRoute: typeof AuthedGroupsNewIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedhomeIndexRoute: AuthedhomeIndexRoute,
  AuthedGroupsNewIndexRoute: AuthedGroupsNewIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicWelcomeIndexRoute: typeof PublicWelcomeIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicWelcomeIndexRoute: PublicWelcomeIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
