/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as PublicWelcomeIndexRouteImport } from './routes/_public/welcome/index'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedGoalsIndexRouteImport } from './routes/_authed/goals/index'
import { Route as AuthedActivityIndexRouteImport } from './routes/_authed/activity/index'
import { Route as AuthedhomeIndexRouteImport } from './routes/_authed/(home)/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SharedJoinInviteCodeRouteImport } from './routes/_shared/join/$inviteCode'
import { Route as PublicLoginOtpRouteImport } from './routes/_public/login/otp'
import { Route as PublicLoginGoogleSyncRouteImport } from './routes/_public/login/google-sync'
import { Route as AuthedItinerariesNewIndexRouteImport } from './routes/_authed/itineraries/new/index'
import { Route as AuthedItinerariesIdIndexRouteImport } from './routes/_authed/itineraries/$id/index'
import { Route as AuthedGroupsNewIndexRouteImport } from './routes/_authed/groups/new/index'
import { Route as AuthedGroupsIdIndexRouteImport } from './routes/_authed/groups/$id/index'
import { Route as AuthedGoalsNewIndexRouteImport } from './routes/_authed/goals/new/index'
import { Route as AuthedGoalsIdIndexRouteImport } from './routes/_authed/goals/$id/index'
import { Route as AuthedGroupsNewParticipantsIndexRouteImport } from './routes/_authed/groups/new/participants/index'
import { Route as AuthedGroupsIdTotalsIndexRouteImport } from './routes/_authed/groups/$id/totals/index'
import { Route as AuthedGroupsIdSettleIndexRouteImport } from './routes/_authed/groups/$id/settle/index'
import { Route as AuthedGroupsIdParticipantsIndexRouteImport } from './routes/_authed/groups/$id/participants/index'
import { Route as AuthedGroupsIdGoalsIndexRouteImport } from './routes/_authed/groups/$id/goals/index'
import { Route as AuthedGroupsIdAddExpenseIndexRouteImport } from './routes/_authed/groups/$id/add-expense/index'
import { Route as AuthedGroupsIdExpenseExpenseIdIndexRouteImport } from './routes/_authed/groups/$id/expense/$expenseId/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicWelcomeIndexRoute = PublicWelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGoalsIndexRoute = AuthedGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityIndexRoute = AuthedActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedhomeIndexRoute = AuthedhomeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedJoinInviteCodeRoute = SharedJoinInviteCodeRouteImport.update({
  id: '/_shared/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginOtpRoute = PublicLoginOtpRouteImport.update({
  id: '/login/otp',
  path: '/login/otp',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginGoogleSyncRoute = PublicLoginGoogleSyncRouteImport.update({
  id: '/login/google-sync',
  path: '/login/google-sync',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedItinerariesNewIndexRoute =
  AuthedItinerariesNewIndexRouteImport.update({
    id: '/itineraries/new/',
    path: '/itineraries/new/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedItinerariesIdIndexRoute =
  AuthedItinerariesIdIndexRouteImport.update({
    id: '/itineraries/$id/',
    path: '/itineraries/$id/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsNewIndexRoute = AuthedGroupsNewIndexRouteImport.update({
  id: '/groups/new/',
  path: '/groups/new/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsIdIndexRoute = AuthedGroupsIdIndexRouteImport.update({
  id: '/groups/$id/',
  path: '/groups/$id/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGoalsNewIndexRoute = AuthedGoalsNewIndexRouteImport.update({
  id: '/goals/new/',
  path: '/goals/new/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGoalsIdIndexRoute = AuthedGoalsIdIndexRouteImport.update({
  id: '/goals/$id/',
  path: '/goals/$id/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsNewParticipantsIndexRoute =
  AuthedGroupsNewParticipantsIndexRouteImport.update({
    id: '/groups/new/participants/',
    path: '/groups/new/participants/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIdTotalsIndexRoute =
  AuthedGroupsIdTotalsIndexRouteImport.update({
    id: '/groups/$id/totals/',
    path: '/groups/$id/totals/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIdSettleIndexRoute =
  AuthedGroupsIdSettleIndexRouteImport.update({
    id: '/groups/$id/settle/',
    path: '/groups/$id/settle/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIdParticipantsIndexRoute =
  AuthedGroupsIdParticipantsIndexRouteImport.update({
    id: '/groups/$id/participants/',
    path: '/groups/$id/participants/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIdGoalsIndexRoute =
  AuthedGroupsIdGoalsIndexRouteImport.update({
    id: '/groups/$id/goals/',
    path: '/groups/$id/goals/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIdAddExpenseIndexRoute =
  AuthedGroupsIdAddExpenseIndexRouteImport.update({
    id: '/groups/$id/add-expense/',
    path: '/groups/$id/add-expense/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedGroupsIdExpenseExpenseIdIndexRoute =
  AuthedGroupsIdExpenseExpenseIdIndexRouteImport.update({
    id: '/groups/$id/expense/$expenseId/',
    path: '/groups/$id/expense/$expenseId/',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedhomeIndexRoute
  '/login/google-sync': typeof PublicLoginGoogleSyncRoute
  '/login/otp': typeof PublicLoginOtpRoute
  '/join/$inviteCode': typeof SharedJoinInviteCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/activity/': typeof AuthedActivityIndexRoute
  '/goals/': typeof AuthedGoalsIndexRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/login/': typeof PublicLoginIndexRoute
  '/welcome/': typeof PublicWelcomeIndexRoute
  '/goals/$id/': typeof AuthedGoalsIdIndexRoute
  '/goals/new/': typeof AuthedGoalsNewIndexRoute
  '/groups/$id/': typeof AuthedGroupsIdIndexRoute
  '/groups/new/': typeof AuthedGroupsNewIndexRoute
  '/itineraries/$id/': typeof AuthedItinerariesIdIndexRoute
  '/itineraries/new/': typeof AuthedItinerariesNewIndexRoute
  '/groups/$id/add-expense/': typeof AuthedGroupsIdAddExpenseIndexRoute
  '/groups/$id/goals/': typeof AuthedGroupsIdGoalsIndexRoute
  '/groups/$id/participants/': typeof AuthedGroupsIdParticipantsIndexRoute
  '/groups/$id/settle/': typeof AuthedGroupsIdSettleIndexRoute
  '/groups/$id/totals/': typeof AuthedGroupsIdTotalsIndexRoute
  '/groups/new/participants/': typeof AuthedGroupsNewParticipantsIndexRoute
  '/groups/$id/expense/$expenseId/': typeof AuthedGroupsIdExpenseExpenseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedhomeIndexRoute
  '/login/google-sync': typeof PublicLoginGoogleSyncRoute
  '/login/otp': typeof PublicLoginOtpRoute
  '/join/$inviteCode': typeof SharedJoinInviteCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/activity': typeof AuthedActivityIndexRoute
  '/goals': typeof AuthedGoalsIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/welcome': typeof PublicWelcomeIndexRoute
  '/goals/$id': typeof AuthedGoalsIdIndexRoute
  '/goals/new': typeof AuthedGoalsNewIndexRoute
  '/groups/$id': typeof AuthedGroupsIdIndexRoute
  '/groups/new': typeof AuthedGroupsNewIndexRoute
  '/itineraries/$id': typeof AuthedItinerariesIdIndexRoute
  '/itineraries/new': typeof AuthedItinerariesNewIndexRoute
  '/groups/$id/add-expense': typeof AuthedGroupsIdAddExpenseIndexRoute
  '/groups/$id/goals': typeof AuthedGroupsIdGoalsIndexRoute
  '/groups/$id/participants': typeof AuthedGroupsIdParticipantsIndexRoute
  '/groups/$id/settle': typeof AuthedGroupsIdSettleIndexRoute
  '/groups/$id/totals': typeof AuthedGroupsIdTotalsIndexRoute
  '/groups/new/participants': typeof AuthedGroupsNewParticipantsIndexRoute
  '/groups/$id/expense/$expenseId': typeof AuthedGroupsIdExpenseExpenseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/login/google-sync': typeof PublicLoginGoogleSyncRoute
  '/_public/login/otp': typeof PublicLoginOtpRoute
  '/_shared/join/$inviteCode': typeof SharedJoinInviteCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/(home)/': typeof AuthedhomeIndexRoute
  '/_authed/activity/': typeof AuthedActivityIndexRoute
  '/_authed/goals/': typeof AuthedGoalsIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_public/welcome/': typeof PublicWelcomeIndexRoute
  '/_authed/goals/$id/': typeof AuthedGoalsIdIndexRoute
  '/_authed/goals/new/': typeof AuthedGoalsNewIndexRoute
  '/_authed/groups/$id/': typeof AuthedGroupsIdIndexRoute
  '/_authed/groups/new/': typeof AuthedGroupsNewIndexRoute
  '/_authed/itineraries/$id/': typeof AuthedItinerariesIdIndexRoute
  '/_authed/itineraries/new/': typeof AuthedItinerariesNewIndexRoute
  '/_authed/groups/$id/add-expense/': typeof AuthedGroupsIdAddExpenseIndexRoute
  '/_authed/groups/$id/goals/': typeof AuthedGroupsIdGoalsIndexRoute
  '/_authed/groups/$id/participants/': typeof AuthedGroupsIdParticipantsIndexRoute
  '/_authed/groups/$id/settle/': typeof AuthedGroupsIdSettleIndexRoute
  '/_authed/groups/$id/totals/': typeof AuthedGroupsIdTotalsIndexRoute
  '/_authed/groups/new/participants/': typeof AuthedGroupsNewParticipantsIndexRoute
  '/_authed/groups/$id/expense/$expenseId/': typeof AuthedGroupsIdExpenseExpenseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/google-sync'
    | '/login/otp'
    | '/join/$inviteCode'
    | '/api/auth/$'
    | '/activity/'
    | '/goals/'
    | '/profile/'
    | '/login/'
    | '/welcome/'
    | '/goals/$id/'
    | '/goals/new/'
    | '/groups/$id/'
    | '/groups/new/'
    | '/itineraries/$id/'
    | '/itineraries/new/'
    | '/groups/$id/add-expense/'
    | '/groups/$id/goals/'
    | '/groups/$id/participants/'
    | '/groups/$id/settle/'
    | '/groups/$id/totals/'
    | '/groups/new/participants/'
    | '/groups/$id/expense/$expenseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/google-sync'
    | '/login/otp'
    | '/join/$inviteCode'
    | '/api/auth/$'
    | '/activity'
    | '/goals'
    | '/profile'
    | '/login'
    | '/welcome'
    | '/goals/$id'
    | '/goals/new'
    | '/groups/$id'
    | '/groups/new'
    | '/itineraries/$id'
    | '/itineraries/new'
    | '/groups/$id/add-expense'
    | '/groups/$id/goals'
    | '/groups/$id/participants'
    | '/groups/$id/settle'
    | '/groups/$id/totals'
    | '/groups/new/participants'
    | '/groups/$id/expense/$expenseId'
  id:
    | '__root__'
    | '/_authed'
    | '/_public'
    | '/_public/login/google-sync'
    | '/_public/login/otp'
    | '/_shared/join/$inviteCode'
    | '/api/auth/$'
    | '/_authed/(home)/'
    | '/_authed/activity/'
    | '/_authed/goals/'
    | '/_authed/profile/'
    | '/_public/login/'
    | '/_public/welcome/'
    | '/_authed/goals/$id/'
    | '/_authed/goals/new/'
    | '/_authed/groups/$id/'
    | '/_authed/groups/new/'
    | '/_authed/itineraries/$id/'
    | '/_authed/itineraries/new/'
    | '/_authed/groups/$id/add-expense/'
    | '/_authed/groups/$id/goals/'
    | '/_authed/groups/$id/participants/'
    | '/_authed/groups/$id/settle/'
    | '/_authed/groups/$id/totals/'
    | '/_authed/groups/new/participants/'
    | '/_authed/groups/$id/expense/$expenseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  SharedJoinInviteCodeRoute: typeof SharedJoinInviteCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/welcome/': {
      id: '/_public/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof PublicWelcomeIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/goals/': {
      id: '/_authed/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AuthedGoalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity/': {
      id: '/_authed/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthedActivityIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/(home)/': {
      id: '/_authed/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedhomeIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shared/join/$inviteCode': {
      id: '/_shared/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof SharedJoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login/otp': {
      id: '/_public/login/otp'
      path: '/login/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof PublicLoginOtpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login/google-sync': {
      id: '/_public/login/google-sync'
      path: '/login/google-sync'
      fullPath: '/login/google-sync'
      preLoaderRoute: typeof PublicLoginGoogleSyncRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/itineraries/new/': {
      id: '/_authed/itineraries/new/'
      path: '/itineraries/new'
      fullPath: '/itineraries/new/'
      preLoaderRoute: typeof AuthedItinerariesNewIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/itineraries/$id/': {
      id: '/_authed/itineraries/$id/'
      path: '/itineraries/$id'
      fullPath: '/itineraries/$id/'
      preLoaderRoute: typeof AuthedItinerariesIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/new/': {
      id: '/_authed/groups/new/'
      path: '/groups/new'
      fullPath: '/groups/new/'
      preLoaderRoute: typeof AuthedGroupsNewIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/': {
      id: '/_authed/groups/$id/'
      path: '/groups/$id'
      fullPath: '/groups/$id/'
      preLoaderRoute: typeof AuthedGroupsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/goals/new/': {
      id: '/_authed/goals/new/'
      path: '/goals/new'
      fullPath: '/goals/new/'
      preLoaderRoute: typeof AuthedGoalsNewIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/goals/$id/': {
      id: '/_authed/goals/$id/'
      path: '/goals/$id'
      fullPath: '/goals/$id/'
      preLoaderRoute: typeof AuthedGoalsIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/new/participants/': {
      id: '/_authed/groups/new/participants/'
      path: '/groups/new/participants'
      fullPath: '/groups/new/participants/'
      preLoaderRoute: typeof AuthedGroupsNewParticipantsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/totals/': {
      id: '/_authed/groups/$id/totals/'
      path: '/groups/$id/totals'
      fullPath: '/groups/$id/totals/'
      preLoaderRoute: typeof AuthedGroupsIdTotalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/settle/': {
      id: '/_authed/groups/$id/settle/'
      path: '/groups/$id/settle'
      fullPath: '/groups/$id/settle/'
      preLoaderRoute: typeof AuthedGroupsIdSettleIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/participants/': {
      id: '/_authed/groups/$id/participants/'
      path: '/groups/$id/participants'
      fullPath: '/groups/$id/participants/'
      preLoaderRoute: typeof AuthedGroupsIdParticipantsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/goals/': {
      id: '/_authed/groups/$id/goals/'
      path: '/groups/$id/goals'
      fullPath: '/groups/$id/goals/'
      preLoaderRoute: typeof AuthedGroupsIdGoalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/add-expense/': {
      id: '/_authed/groups/$id/add-expense/'
      path: '/groups/$id/add-expense'
      fullPath: '/groups/$id/add-expense/'
      preLoaderRoute: typeof AuthedGroupsIdAddExpenseIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups/$id/expense/$expenseId/': {
      id: '/_authed/groups/$id/expense/$expenseId/'
      path: '/groups/$id/expense/$expenseId'
      fullPath: '/groups/$id/expense/$expenseId/'
      preLoaderRoute: typeof AuthedGroupsIdExpenseExpenseIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedhomeIndexRoute: typeof AuthedhomeIndexRoute
  AuthedActivityIndexRoute: typeof AuthedActivityIndexRoute
  AuthedGoalsIndexRoute: typeof AuthedGoalsIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
  AuthedGoalsIdIndexRoute: typeof AuthedGoalsIdIndexRoute
  AuthedGoalsNewIndexRoute: typeof AuthedGoalsNewIndexRoute
  AuthedGroupsIdIndexRoute: typeof AuthedGroupsIdIndexRoute
  AuthedGroupsNewIndexRoute: typeof AuthedGroupsNewIndexRoute
  AuthedItinerariesIdIndexRoute: typeof AuthedItinerariesIdIndexRoute
  AuthedItinerariesNewIndexRoute: typeof AuthedItinerariesNewIndexRoute
  AuthedGroupsIdAddExpenseIndexRoute: typeof AuthedGroupsIdAddExpenseIndexRoute
  AuthedGroupsIdGoalsIndexRoute: typeof AuthedGroupsIdGoalsIndexRoute
  AuthedGroupsIdParticipantsIndexRoute: typeof AuthedGroupsIdParticipantsIndexRoute
  AuthedGroupsIdSettleIndexRoute: typeof AuthedGroupsIdSettleIndexRoute
  AuthedGroupsIdTotalsIndexRoute: typeof AuthedGroupsIdTotalsIndexRoute
  AuthedGroupsNewParticipantsIndexRoute: typeof AuthedGroupsNewParticipantsIndexRoute
  AuthedGroupsIdExpenseExpenseIdIndexRoute: typeof AuthedGroupsIdExpenseExpenseIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedhomeIndexRoute: AuthedhomeIndexRoute,
  AuthedActivityIndexRoute: AuthedActivityIndexRoute,
  AuthedGoalsIndexRoute: AuthedGoalsIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
  AuthedGoalsIdIndexRoute: AuthedGoalsIdIndexRoute,
  AuthedGoalsNewIndexRoute: AuthedGoalsNewIndexRoute,
  AuthedGroupsIdIndexRoute: AuthedGroupsIdIndexRoute,
  AuthedGroupsNewIndexRoute: AuthedGroupsNewIndexRoute,
  AuthedItinerariesIdIndexRoute: AuthedItinerariesIdIndexRoute,
  AuthedItinerariesNewIndexRoute: AuthedItinerariesNewIndexRoute,
  AuthedGroupsIdAddExpenseIndexRoute: AuthedGroupsIdAddExpenseIndexRoute,
  AuthedGroupsIdGoalsIndexRoute: AuthedGroupsIdGoalsIndexRoute,
  AuthedGroupsIdParticipantsIndexRoute: AuthedGroupsIdParticipantsIndexRoute,
  AuthedGroupsIdSettleIndexRoute: AuthedGroupsIdSettleIndexRoute,
  AuthedGroupsIdTotalsIndexRoute: AuthedGroupsIdTotalsIndexRoute,
  AuthedGroupsNewParticipantsIndexRoute: AuthedGroupsNewParticipantsIndexRoute,
  AuthedGroupsIdExpenseExpenseIdIndexRoute:
    AuthedGroupsIdExpenseExpenseIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicLoginGoogleSyncRoute: typeof PublicLoginGoogleSyncRoute
  PublicLoginOtpRoute: typeof PublicLoginOtpRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
  PublicWelcomeIndexRoute: typeof PublicWelcomeIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginGoogleSyncRoute: PublicLoginGoogleSyncRoute,
  PublicLoginOtpRoute: PublicLoginOtpRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
  PublicWelcomeIndexRoute: PublicWelcomeIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  SharedJoinInviteCodeRoute: SharedJoinInviteCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
