name: Deploy Web

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main
    paths:
      - "apps/webapp/**"
      - ".github/workflows/deploy-web.yml"

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run --filter @vornway/web build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "apps/webapp"
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy
